### ISSUE TITLE
Issue with turbo_mode in Jupyter Lab

### ISSUE THREAD

**Issue by RajK853** [MountRouke/DerkGymIssues#10]
I am trying to run the `DerkEnv` in `turbo_mode` in Jupyter Lab using the following command: 
```python
from gym_derk.envs import DerkEnv

env = DerkEnv(session_args={"turbo_mode": True})

```
However, the simulation is not running in the headless mode and it is still being rendered on the chromium-browser.

**Comment by FredrikNoren** [comment]
Yeah unfortunately chromium doesn't support headless WebGL2 yet, which is required for the game to run. This is the relevant issue: https://bugs.chromium.org/p/chromium/issues/detail?id=765284
