### ISSUE TITLE
Additional game state and general reward functions

### ISSUE THREAD

**Issue by bwitherspoon** [MountRouke/DerkGymIssues#11]
This is an enhancement proposal to make more of the game state information available.

For example, some information that I would like to monitor would be some of the individual events used in the reward function.

Maybe this could be returned in the `info` dictionary from each step. For example:

```py
info["damageEnemyStatue"] = np.array([0, 1, 0], dtype=np.float32)
```

Where `1` is a binary indicator of the event for each agent from the _previous_ step

My motivation is to better monitor the progress of learning and the effects of changes in my reward function and hyperparameters. However, I assume someone could also incorporate this information into their observation as some sort of "afterstate". If required, this information could be easily excluded in a competition where players typically do not control the environment.

Another interesting outcome would be the possibility of user defined (possibly dynamic) reward functions which could be calculated from the afterstate information given in `info`. Maybe this could even be incorporated into the environment by having a user defined reward class:

```py
class MyReward(DerkReward):
    def __init__(self, env: DerkEnv) -> None:
        ...
    
    def reset(self, env: DerkEnv) -> None:
        ...

    def __call__(self, state: Dict[str, Any]) -> float:
        ...
```

```py
env = DerkEnv(reward_class=MyReward)
```

**Comment by FredrikNoren** [comment]
Hm so the problem is that there aren't really any events in the game, since the entire game state runs on the GPU it's just a bunch of functions that transform it from prev state -> next state. I think I could expose the entire state as a JSON or something and from that you could probably extract any number of signals, if that would help?

**Comment by bwitherspoon** [comment]
That would work great. I am wondering if it would have a significant effect on runtime and if it would need to be optional.

**Comment by FredrikNoren** [comment]
Alright, I just pushed a new version (1.0.0) with a feature to read the entire game state. There's a lot in there though, so be warned :)

**Comment by bwitherspoon** [comment]
Oh wow. That is a lot. I'll see if I can make sense of it. Unfortunately, as expected the effect on runtime is significant. I was hoping there would be a way to reuse whatever logic already calculates the reward (which is fast) and just make it more flexible.
