### ISSUE TITLE
Expose observations, actions and optional state information directly on GPU

### ISSUE THREAD

**Issue by ViktorM** [MountRouke/DerkGymIssues#12]
As the can run on GPU it would good to have access to observations as well as send actions directly on GPU as PyTorch tensors, without copying to CPU, transforming to np arrays, and then doing the inverse operation by RL algorithm.

In addition, it would be good to have access to the additional state information during training time, also exposed and GPU PyTorch tensors.

**Comment by FredrikNoren** [comment]
Hi @ViktorM. Yeah I agree, that would be great. The problem right now is that the game runs as a webapp in chrome, so to transfer any information into the game it needs to pass through some channel in chrome, which are all CPU based :/ I think it would basically take a complete rewrite to accomplish the above

**Comment by ViktorM** [comment]
Thanks for the feedback!
