### ISSUE TITLE
Setting a initial item of Derklings

### ISSUE THREAD

**Issue by kimbring2** [MountRouke/DerkGymIssues#18]
Hello,

I am finding a way to set a default item of the each Derklings when I start a game. I need to make narrow down the item combination to check my model works well.

I thought I can access to source code when I subscribe to academic research. However, I can not find a way for it.

Please help me!

Thank you

**Comment by kimbring2** [comment]
Oh, sorry. I just check I need to send a email to contact@mountrouke.com.

**Comment by FredrikNoren** [comment]
@kimbring2 Hi! Is this what you're looking for: http://docs.gym.derkgame.com/#configuring-your-derklings ? That's how you can configure which items are assigned to the derklings. I also just added you for source code access, here's the repository: https://github.com/MountRouke/Derk (Think you should get an email as well)

**Comment by kimbring2** [comment]
@FredrikNoren Thank you for quick invitation. I can continue my work :+1:

**Comment by FredrikNoren** [comment]
@kimbring2 Great! Best of luck
