### ISSUE TITLE
Installation: Download times out

### ISSUE THREAD

**Issue by 222464** [MountRouke/DerkGymIssues#2]
Hi,

I tried installing, but I receive:

`Collecting gym-derk
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/09/22/361df6fa64a9c4228db93615bf6fa8ca1d453d4c0f28d639811b14499f03/gym_derk-0.3.17-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/09/22/361df6fa64a9c4228db93615bf6fa8ca1d453d4c0f28d639811b14499f03/gym_derk-0.3.17-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/09/22/361df6fa64a9c4228db93615bf6fa8ca1d453d4c0f28d639811b14499f03/gym_derk-0.3.17-py3-none-any.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/09/22/361df6fa64a9c4228db93615bf6fa8ca1d453d4c0f28d639811b14499f03/gym_derk-0.3.17-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/09/22/361df6fa64a9c4228db93615bf6fa8ca1d453d4c0f28d639811b14499f03/gym_derk-0.3.17-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/09/22/361df6fa64a9c4228db93615bf6fa8ca1d453d4c0f28d639811b14499f03/gym_derk-0.3.17-py3-none-any.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)"))`

Please advise/fix!

**Comment by 222464** [comment]
I retried a couple of times, and it eventually worked for some reason!

**Comment by FredrikNoren** [comment]
Happy to hear it worked out! I think that was a pip issue. If anyone else runs into something like it this thread seems to offer a solution: (increase timeout) https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port
