### ISSUE TITLE
Browser closed unexpectedly error when running in server

### ISSUE THREAD

**Issue by bupticybee** [MountRouke/DerkGymIssues#5]
I try to run Derkgym env in a server environment(without screens). I run the testing script in https://gym.derkgame.com/ and get the following error:

> 
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     env = DerkEnv(
>   File "/home/tiger/.local/lib/python3.7/site-packages/gym_derk/envs/derk_env.py", line 75, in __init__
>     asyncio.get_event_loop().run_until_complete(self.app.start())
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "/home/tiger/.local/lib/python3.7/site-packages/gym_derk/derk_app_instance.py", line 145, in start
>     handleSIGINT=False,
>   File "/home/tiger/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
>     return await Launcher(options, **kwargs).launch()
>   File "/home/tiger/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
>     self.browserWSEndpoint = get_ws_endpoint(self.url)
>   File "/home/tiger/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
>     raise BrowserError('Browser closed unexpectedly:\n')
> pyppeteer.errors.BrowserError: Browser closed unexpectedly:
> 

Am I doing anything wrong here?

**Comment by FredrikNoren** [comment]
Hi,

You will need either xvfb (run on CPU) or virtualgl (run on GPU) to run on a server environment. See this docker example of how to use xvfb: https://github.com/MountRouke/DerkAppInstanceDockerized

Virtualgl is a bit more complicated to set up and depends on your local system (which graphics card etc).

**Comment by FredrikNoren** [comment]
I've added some more OS/environment specific instructions here: http://docs.gym.derkgame.com/#installation-running-os-specific-instructions . Lmk if that doesn't solve the issue.
