### ISSUE TITLE
Observations and actions key enumerations without environment instance

### ISSUE THREAD

**Issue by bwitherspoon** [MountRouke/DerkGymIssues#7]
Could the _Observations_ and _Actions_ enumerations be made available as Enum classes outside an environment instance? In the AIcrowd competition, for example, we are not given access to an environment instance.

So instead of the functional API:

```python
self.action_keys = enum.Enum('Actions', ['MoveX', 'Rotate', 'ChaseFocus', 'CastingSlot', 'ChangeFocus'], start=0)
```

An Enum class:

```python
class Actions(enum.Enum):
    MoveX: 0
    Rotate:
    ...

# Stay compatible
self.action_keys = Actions
```
maybe nested

```python
from gym_derk import DerkSession

actions[DerkSession.Actions.Rotate.value] = 0
```
or at the module or package level

```python
from gym_derk import DerkActions

actions[DerkActions.Rotate.value] = 0
```

**Comment by FredrikNoren** [comment]
@bwitherspoon Yup, that's much better. I've implemented and deployed this in version [0.16.0](http://docs.gym.derkgame.com/#changelog); there are now enum classes for ObservationKeys, ActionKeys and TeamStatsKeys.
